language: python
python:
  - "2.7"
before_install: "sudo apt-get install libldap2-dev libsasl2-dev"
install: "make install_dev install"
script: "make pep8 test_with_coverage"
after_success:
  - "coveralls"
